spring:
  application:
    name: mini-forum

  datasource:
    url: jdbc:mysql://localhost:3306/board
    username: hye2021
    password: hye2021
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
    port: 80
